name: CI for Ch08 using java platform

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - run: cd Ch08/
      - name: Test with Maven for Ch08
        run: mvn test